[metadata]
name = rlquantopt
version = 1.0.0
description = RLQuantOpt - Optimising quantum fate fidelity with Reinforcement Learning
;long_description = file: wiki/Home.md
;long_description_content_type = text/markdown
license = Proprietary
author = Leander Grech
author_email = leander.grech@um.edu.mt
url = https://dsrg-ict.research.um.edu.mt/lgrec12/rlquantopt.git
maintainers =
    'Leander Grech <leander.grech@um.edu.mt>'
    'Mirko Consiglio <mirko.consiglio@um.edu.mt>'

[options]
packages=find:
zip_safe = True
include_package_data = True
install_requires =
    setuptools
    numpy
    matplotlib
;    torch
;    torchvision
    tqdm
;    PyYAML
    qutip
    qutip-qip
    pdflatex

;[options.entry_points]
;console_scripts =
;    llm-comino-eval-16k = retics.runners.llm_comino_eval_16k:main